package lexer

// TokenKind represents the type of a lexical token.
type TokenKind int

const (
	TOK_EOF TokenKind = iota
	TOK_INVALID

	TOK_IDENT
	TOK_INT_LIT
	TOK_FLOAT_LIT
	TOK_STRING_LIT

	TOK_KW_FN
	TOK_KW_IMPORT
	TOK_KW_RETURN
	TOK_KW_LET
	TOK_KW_CONST
	TOK_KW_IF
	TOK_KW_ELIF
	TOK_KW_ELSE
	TOK_KW_WHILE
	TOK_KW_FOR
	TOK_KW_MATCH
	TOK_KW_BREAK
	TOK_KW_CONTINUE
	TOK_KW_TRUE
	TOK_KW_FALSE
	TOK_KW_VOID
	TOK_KW_INT
	TOK_KW_FLOAT
	TOK_KW_BOOL
	TOK_KW_STRING
	TOK_KW_AMBA
	TOK_KW_RUSDI
	TOK_KW_FUAD
	TOK_KW_IMUT

	TOK_PLUS
	TOK_PLUS_PLUS
	TOK_MINUS
	TOK_MINUS_MINUS
	TOK_STAR
	TOK_SLASH
	TOK_PERCENT
	TOK_BANG
	TOK_ASSIGN
	TOK_PLUS_ASSIGN
	TOK_MINUS_ASSIGN
	TOK_STAR_ASSIGN
	TOK_SLASH_ASSIGN
	TOK_PERCENT_ASSIGN

	TOK_EQ
	TOK_NE
	TOK_LT
	TOK_LE
	TOK_GT
	TOK_GE
	TOK_AND_AND
	TOK_OR_OR
	TOK_ARROW
	TOK_FAT_ARROW

	TOK_LPAREN
	TOK_RPAREN
	TOK_LBRACE
	TOK_RBRACE
	TOK_LBRACKET
	TOK_RBRACKET
	TOK_COMMA
	TOK_COLON
	TOK_SEMI
)

// Token represents a single lexical token.
type Token struct {
	Kind  TokenKind
	Value string // The raw text of the token
	Line  int
	Col   int
}

// Name returns the string name of a TokenKind.
func (k TokenKind) Name() string {
	names := map[TokenKind]string{
		TOK_EOF: "EOF", TOK_INVALID: "INVALID",
		TOK_IDENT: "IDENT", TOK_INT_LIT: "INT_LIT", TOK_FLOAT_LIT: "FLOAT_LIT", TOK_STRING_LIT: "STRING_LIT",
		TOK_KW_FN: "KW_FN", TOK_KW_IMPORT: "KW_IMPORT", TOK_KW_RETURN: "KW_RETURN",
		TOK_KW_LET: "KW_LET", TOK_KW_CONST: "KW_CONST", TOK_KW_IF: "KW_IF", TOK_KW_ELIF: "KW_ELIF",
		TOK_KW_ELSE: "KW_ELSE", TOK_KW_WHILE: "KW_WHILE", TOK_KW_FOR: "KW_FOR",
		TOK_KW_MATCH: "KW_MATCH", TOK_KW_BREAK: "KW_BREAK", TOK_KW_CONTINUE: "KW_CONTINUE",
		TOK_KW_TRUE: "KW_TRUE", TOK_KW_FALSE: "KW_FALSE", TOK_KW_VOID: "KW_VOID",
		TOK_KW_INT: "KW_INT", TOK_KW_FLOAT: "KW_FLOAT", TOK_KW_BOOL: "KW_BOOL", TOK_KW_STRING: "KW_STRING",
		TOK_KW_AMBA: "KW_AMBA", TOK_KW_RUSDI: "KW_RUSDI", TOK_KW_FUAD: "KW_FUAD", TOK_KW_IMUT: "KW_IMUT",
		TOK_PLUS: "PLUS", TOK_PLUS_PLUS: "PLUS_PLUS", TOK_MINUS: "MINUS", TOK_MINUS_MINUS: "MINUS_MINUS",
		TOK_STAR: "STAR", TOK_SLASH: "SLASH", TOK_PERCENT: "PERCENT", TOK_BANG: "BANG",
		TOK_ASSIGN: "ASSIGN", TOK_PLUS_ASSIGN: "PLUS_ASSIGN", TOK_MINUS_ASSIGN: "MINUS_ASSIGN",
		TOK_STAR_ASSIGN: "STAR_ASSIGN", TOK_SLASH_ASSIGN: "SLASH_ASSIGN", TOK_PERCENT_ASSIGN: "PERCENT_ASSIGN",
		TOK_EQ: "EQ", TOK_NE: "NE", TOK_LT: "LT", TOK_LE: "LE", TOK_GT: "GT", TOK_GE: "GE",
		TOK_AND_AND: "AND_AND", TOK_OR_OR: "OR_OR", TOK_ARROW: "ARROW", TOK_FAT_ARROW: "FAT_ARROW",
		TOK_LPAREN: "LPAREN", TOK_RPAREN: "RPAREN", TOK_LBRACE: "LBRACE", TOK_RBRACE: "RBRACE",
		TOK_LBRACKET: "LBRACKET", TOK_RBRACKET: "RBRACKET", TOK_COMMA: "COMMA", TOK_COLON: "COLON", TOK_SEMI: "SEMI",
	}
	if n, ok := names[k]; ok {
		return n
	}
	return "<unknown>"
}
